version: '3'

services:
  redis:
    # restart: always
    image: redis:latest
    ports:
     - "6379:6379"
    volumes:
     - redis_data:/data

  db:
    # restart: always
    container_name: 'db'
    image: postgres:10.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    # restart: always
    container_name: 'web'
    env_file: .env
    build: .
    command: /src/entrypoint.sh
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
