# Generated by Django 2.1.5 on 2019-02-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peakuser',
            name='bio',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
