# Generated by Django 2.1.5 on 2019-02-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='resort_address_line2',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
