# Generated by Django 2.1.5 on 2019-02-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='resort_altitude',
            field=models.IntegerField(blank=True),
        ),
    ]
