# Generated by Django 2.1.5 on 2019-02-06 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190205_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peakuser',
            name='user_groups_belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Team'),
        ),
        migrations.AlterField(
            model_name='peakuser',
            name='user_profile_picture',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
