# Generated by Django 2.1.5 on 2019-02-05 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20190205_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resort',
            name='resort_teams',
        ),
    ]
