# Generated by Django 2.1.5 on 2019-02-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20190205_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='resort_location_latitude',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='resort',
            name='resort_location_longitude',
            field=models.CharField(max_length=64),
        ),
    ]
